External links PWA page
mozilla-mobile/testapp pull request #6
Opened 2022-01-26 12:50 UTC by AndiAJ

2022-01-27 17:41 UTC, AaronMT requested changes

2022-01-27 17:41 UTC, AaronMT commented on externalLinks.html
> +    <a href="mailto://notta-r3al-3mail@gmail.com">Email link</a>
Lets use `example@example.com`

2022-01-27 17:41 UTC, AaronMT commented on externalLinks.html
> +    <a href="tel://+1-234-555-1212">Telephone link</a>
Let's use `tel://1234567890`

2022-01-28 06:25 UTC, AndiAJ commented on externalLinks.html
> +    <a href="tel://+1-234-555-1212">Telephone link</a>
Done and works properly.

2022-01-28 06:25 UTC, AndiAJ commented on externalLinks.html
> +    <a href="mailto://notta-r3al-3mail@gmail.com">Email link</a>
Done and works properly.

2022-01-28 14:18 UTC, AaronMT approved these changes

2022-01-28 14:18 UTC, merged